[supervisord]
nodaemon=true
user=root
logfile=/var/log/supervisor/supervisord.log
pidfile=/var/run/supervisord.pid

[program:php]
command=%(ENV_SUPERVISOR_PHP_COMMAND)s
user=%(ENV_SUPERVISOR_PHP_USER)s
environment=LARAVEL_SAIL="1"
stdout_logfile=/dev/stdout
stdout_logfile_maxbytes=0
stderr_logfile=/dev/stderr
stderr_logfile_maxbytes=0

[program:reverb]
command=/usr/bin/php -d variables_order=EGPCS /var/www/html/artisan reverb:start --host=0.0.0.0 --port=6001
user=%(ENV_SUPERVISOR_PHP_USER)s
environment=LARAVEL_SAIL="1"
autostart=true
autorestart=true
stdout_logfile=/var/www/html/storage/logs/reverb.log
stdout_logfile_maxbytes=5MB
stderr_logfile=/var/www/html/storage/logs/reverb-error.log
stderr_logfile_maxbytes=5MB
stopwaitsecs=3600

[program:mqtt-listener]
command=/usr/bin/php -d variables_order=EGPCS /var/www/html/artisan mqtt:listen
user=%(ENV_SUPERVISOR_PHP_USER)s
environment=LARAVEL_SAIL="1"
autostart=true
autorestart=true
stdout_logfile=/var/www/html/storage/logs/mqtt-listener.log
stdout_logfile_maxbytes=5MB
stderr_logfile=/var/www/html/storage/logs/mqtt-listener-error.log
stderr_logfile_maxbytes=5MB
stopwaitsecs=3600

[program:vite]
command=/usr/bin/npm run dev
directory=/var/www/html
user=%(ENV_SUPERVISOR_PHP_USER)s
environment=LARAVEL_SAIL="1"
autostart=true
autorestart=true
stdout_logfile=/var/www/html/storage/logs/vite.log
stdout_logfile_maxbytes=5MB
stderr_logfile=/var/www/html/storage/logs/vite-error.log
stderr_logfile_maxbytes=5MB
stopwaitsecs=10
